variables:
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}

before_script:
  - echo $CI_JOB_STAGE

stages:
  - testing
  - quality
  - build
  - scanning
  - summary
  - deploy

testing:
  image: alpine
  stage: testing
  script:
    - echo $CI_JOB_STAGE
  artifacts:
    paths:
      - coverage.xml
      - report.xml
  only:
    - main
    - practica-01

sonarqube:
  image: alpine
  stage: quality
  variables:
    SONAR_PROJECT_BASE_DIR: "./"
  script:
    - echo "Ejecutando sonarqube"
  dependencies:
    - testing
  only:
    - main
    - practica-01

docker-build:
  image:
      name: docker:28.0.2
  # services Dind es necesario para ejecutar Docker
  services:
    - docker:28.0.2-dind
  stage: build
  script:
   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
   - echo $IMAGE
  only:
    - main
    - practica-01

scanning:
  stage: scanning
  variables:
    # TRIVY necesita User y Pass para poder acceder a la Imagen
    TRIVY_USERNAME: ${CI_REGISTRY_USER}
    TRIVY_PASSWORD: ${CI_REGISTRY_PASSWORD}
  image:
    name: alpine
    entrypoint: [ "" ]
  dependencies:
    - docker-build
  cache:
    key: trivy-cache
    paths:
      - .cache
  script:
    - echo $CI_JOB_STAGE
  artifacts:
    paths:
      - scanning-report.json # gitlab-codequality
      - gl-dependency-scanning-report.json # spdx-json
  only:
    - main
    - practica-01


pages:
  stage: summary
  image: alpine
  script:
    - echo $CI_JOB_STAGE
    - mkdir -p public
    - echo "<html><body><h1>Hola Mundo</h1></body></html>" > public/index.html
  dependencies:
    - testing
    - scanning
  artifacts:
    paths:
      - public
  only:
    - main
    - practica-01


deploy:
  stage: deploy
  image: 
    # Usar una imagen de Alpine para el job de deploy
    name: alpine:3.21.3
    entrypoint: [""]
  before_script:
    # Kubectl y AWS CLI
    - apk add --no-cache curl bash ca-certificates aws-cli
    - export KUBECTL_VERSION=v1.29.3
    - curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
    - curl -LO "https://dl.k8s.io/${KUBECTL_VERSION}/bin/linux/amd64/kubectl.sha256"
    - echo "$(cat kubectl.sha256)  kubectl" | sha256sum -c -
    - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    # Verificar instalación de kubectl y aws-cli
    - aws --version
    - kubectl version --client
    # Configurar credenciales de AWS
    - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
    - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
    - aws configure set aws_session_token ${AWS_SESSION_TOKEN}
    - aws configure set region ${AWS_DEFAULT_REGION}
    # Verificar que las credenciales estén configuradas
    - aws sts get-caller-identity
    # Configurar kubectl para EKS
    - aws eks update-kubeconfig --name eks-2025-1 --region ${AWS_DEFAULT_REGION}
  script:
    - aws --version
    - kubectl version --client
    # Actualizar el deployment de Kubernetes con la nueva imagen
    # deployment: telegram-bot
    # container: telegram-bot
    # namespace: grupo00
    # image: registry.gitlab.com/public-unrn/telegram-bot-ia-talk-database:c1ba4126
    #- kubectl set image 
  dependencies:
    - pages
  only:
    - main