apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: grupo00
data:
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "bot"
  DB_DIALECT: "PostgreSQL"
  DB_HOST: "......"
  DB_PORT: "5432"
